-- 固定资产第一期表结构（可重复执行）

CREATE TABLE IF NOT EXISTS `asset_category` (
  `id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',
  `book_id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '所属账套',
  `code` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '类别编码',
  `name` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '类别名称',
  `depreciation_method` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT 'STRAIGHT_LINE' COMMENT '折旧方法',
  `useful_life_years` int DEFAULT NULL COMMENT '预计使用年限(年)',
  `useful_life_months` int NOT NULL COMMENT '预计使用期数(月)',
  `residual_rate` decimal(10,4) NOT NULL DEFAULT '5.0000' COMMENT '预计净残值率%',
  `fixed_asset_subject_id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '固定资产科目',
  `accum_depr_subject_id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '累计折旧科目',
  `remark` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
  `created_by` varchar(45) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `deleted` varchar(1) DEFAULT 'n' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asset_category_book_code` (`book_id`,`code`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='固定资产类别';

CREATE TABLE IF NOT EXISTS `fixed_asset` (
  `id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',
  `book_id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '所属账套',
  `code` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '资产编码',
  `name` varchar(128) COLLATE utf8mb4_bin NOT NULL COMMENT '资产名称',
  `category_id` varchar(45) COLLATE utf8mb4_bin NOT NULL COMMENT '资产类别',
  `dept_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '使用部门',
  `start_use_date` date NOT NULL COMMENT '开始使用日期',
  `entry_period` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT '录入期间 yyyy-MM',
  `quantity` int NOT NULL DEFAULT 1 COMMENT '数量',
  `spec` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '规格型号',
  `location` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '存放地点',
  `user_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '使用人',
  `status` varchar(16) COLLATE utf8mb4_bin NOT NULL DEFAULT 'IN_USE' COMMENT 'IN_USE|SUSPENDED|DISPOSED',
  `disposed_period` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '清理所属期',
  `suspended_period` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '暂停计提起始期',
  `depreciation_method` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '折旧方法',
  `useful_life_months` int DEFAULT NULL COMMENT '预计使用期数(月)',
  `expected_total_work` decimal(18,4) DEFAULT NULL COMMENT '预计总工作量',
  `residual_rate` decimal(10,4) NOT NULL DEFAULT '5.0000' COMMENT '残值率%',
  `original_value` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '原值',
  `tax_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `impairment` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '减值准备',
  `depreciated_periods` int NOT NULL DEFAULT 0 COMMENT '已折旧期数',
  `opening_accum_depr` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '期初累计折旧(录入时)',
  `accum_depr` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '当前累计折旧',
  `year_depr` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '本年已折旧',
  `fixed_asset_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `purchase_counterpart_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `tax_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `accum_depr_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `expense_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `disposal_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `impairment_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `impairment_counterpart_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `remark` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL,
  `dispose_voucher_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '清理凭证ID',
  `purchase_voucher_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '购入凭证ID',
  `created_by` varchar(45) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `deleted` varchar(1) DEFAULT 'n',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fixed_asset_book_code` (`book_id`,`code`,`deleted`),
  KEY `idx_fixed_asset_category` (`book_id`,`category_id`),
  KEY `idx_fixed_asset_status` (`book_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='固定资产卡片';

CREATE TABLE IF NOT EXISTS `fixed_asset_work` (
  `id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `book_id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `asset_id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `year_period` varchar(7) COLLATE utf8mb4_bin NOT NULL COMMENT 'yyyy-MM',
  `period_work` decimal(18,4) NOT NULL DEFAULT '0.0000',
  `created_by` varchar(45) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `deleted` varchar(1) DEFAULT 'n',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fixed_asset_work` (`book_id`,`asset_id`,`year_period`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='固定资产本期工作量';

CREATE TABLE IF NOT EXISTS `fixed_asset_accrual` (
  `id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `book_id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `year_period` varchar(7) COLLATE utf8mb4_bin NOT NULL,
  `voucher_date` date DEFAULT NULL,
  `voucher_word` varchar(8) COLLATE utf8mb4_bin DEFAULT '记',
  `summary` varchar(128) COLLATE utf8mb4_bin DEFAULT '计提折旧费用',
  `voucher_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `status` varchar(16) COLLATE utf8mb4_bin NOT NULL DEFAULT 'DONE' COMMENT 'DONE',
  `created_by` varchar(45) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `deleted` varchar(1) DEFAULT 'n',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fixed_asset_accrual` (`book_id`,`year_period`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='固定资产本期计提头';

CREATE TABLE IF NOT EXISTS `fixed_asset_depr` (
  `id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `book_id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `asset_id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `year_period` varchar(7) COLLATE utf8mb4_bin NOT NULL,
  `accrual_id` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `depr_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `expense_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `accum_depr_subject_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `dept_id` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `method` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL,
  `period_work` decimal(18,4) DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `deleted` varchar(1) DEFAULT 'n',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fixed_asset_depr` (`book_id`,`asset_id`,`year_period`,`deleted`),
  KEY `idx_fixed_asset_depr_accrual` (`accrual_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='固定资产期间折旧明细';
