kaptcha.border=no
kaptcha.image.width=100
kaptcha.image.height=50
kaptcha.obscurificator.impl=com.google.code.kaptcha.impl.WaterRipple
kaptcha.noise.impl=com.google.code.kaptcha.impl.DefaultNoise
kaptcha.textproducer.impl=com.google.code.kaptcha.text.impl.DefaultTextCreator
kaptcha.word.impl=com.google.code.kaptcha.text.impl.DefaultWordRenderer
kaptcha.textproducer.char.length=4
kaptcha.textproducer.char.string=0123456789
kaptcha.textproducer.font.names=Arial,Courier
kaptcha.textproducer.font.size=40
kaptcha.background.clear.from=white
kaptcha.background.clear.to=white
